### PR TITLE
more typescript errors and warnings corrected

### PR DESCRIPTION
**Pull request by brainlid**
I'd like your feedback on these changes. I'm not sure how you feel about using a "require" instead of an "import" when there are no current typings for a module?

I added the "require" declaration to allow for this by the following:

`typings install require --ambient --save`

This leaves only 1 more import error for "redux-immutable" which I haven't solved yet.

I also changed the way devToolsExtension is called in the store. It follows some other examples I've seen and adds a type cast on window to avoid warnings/errors. It also makes it easier to add more enhancers like loggers, etc.

Let me know what you think.

### CODE REVIEW

**Comment by janjarfalk** [comment]
Wow, thanks! 

I'm not to fond of mixing `require` and `import`. Especially not in a boilerplate. 
I much rather create typings myself.

https://github.com/janjarfalk/ionic2-angular2-ts-redux-boilerplate/commit/3847054f9dcaa228155f270516f3bc7508968be8

**Comment by brainlid** [comment]
Thanks for the console log cleanup. Forgot to take those out.

**Comment by janjarfalk** [comment]
I found a couple of redux-immutable typings, but i'm not sure how I should use them.
https://www.npmjs.com/package/@types/redux-immutable
Do you know?

Typescript is very new to me.

**Comment by brainlid** [comment]
I gave it a shot and this worked fine. Go figure. :)

`typings install redux-immutable --ambient --save` 

It installed a typings version for 3.0.5 and the project is using version 3.0.6, but seems to work just fine. 

typings.json
`    "redux-immutable": "registry:dt/redux-immutable#3.0.5+20160316155526",`

package.json
`    "redux-immutable": "^3.0.6",`

This added a new typescript error...

```
TypeScript error: /ionic2-angular2-ts-redux-boilerplate/app/stores/store.ts(12,27): Error TS2345: Argument of type 'Object' is not assignable to parameter of type '<A extends Action>(state: any, action: A) => any'.
  Type 'Object' provides no match for the signature '<A extends Action>(state: any, action: A): any'
```

I haven't had a chance to try and solve it yet. 

Typescript is also new to me. :smile: 

Currently I'm exploring how to get [the "select pattern"](https://github.com/angular-redux/ng2-redux#usage) method working for ng2-redux. It uses angular2 observers and is recommended as the preferred approach. Personally, I prefer ReactJS. But I'm creating an Ionic2 app and this is the best approach for my cross-platform needs.

**Pull request merged**
